# Global
array_length: 64
delta_f: 0.1953125 # MHz
delta_t: 2 # s
frequencies: # MHz
  [
    57.617188,
    57.812500,
    58.007812,
    58.203124,
    58.398436,
    58.593752,
    58.789064,
    58.984376,
    61.132812,
    61.328124,
    61.523436,
    61.718752,
    61.914064,
    62.109376,
    62.304688,
    62.500000,
  ]

# LPF
fits_directory: "/project/druhe/ASf_201909011855/"
# Indices [start, stop] that specify the location of the time-stamp in the filename.
timestamp_start_stop: [0, 19]
# Indices [start, stop] that specify the location of subband in the filename.
subband_start_stop: [21, 25]
n_timesteps: -1 # -1 if unlimited.
detection_radius: 448 # Pixels
image_size: 1024 # Pixels
kappa: 5
center_sigma: 21 # Sigma of Gaussian used for background estimation.
scale_sigma: 21
sigma_clipping_maxiter: 1
output_folder: "./runs/"
mmap_n_sources: 6000 # Make sure this is large enough.
use_quality_control: true
box_size: 16 # Pixels
separation_crit: 1. # Degrees
nn_checkpoint: "data/nn/epoch_32.ckpt"
cache_size: -1 # -1 if unlimited.

# Simulation
nparams: 4
dm_range: [0, 512]
fluence_range: [0.0, 32]
width_range: [0, 16]
spec_ind_range: [-4, 4]
simulation_output_folder: "data/transient_sim/a6"
nevents: 8192

# Neural Network
nn_output_folder: "data/nn/"
lr: 0.001
epochs: 32
noise_path: "data/noise/noise.npy" # Optional, (put 'null' if not available.)
noise_multiplier: 1 # Noise value, compare with fluence value.
batch_size: 32
num_workers: 4 # Used for data-loading during training.

# Optional: Noise Extractor
n_arrays: 4096
num_patches_per_image: 512
noise_output_folder: "data/noise/"
