# Global
array_length: 512
df: 195312.5
dt: 1
frequencies:
  [
    64.84375,
    64.0625,
    63.4765625,
    62.6953125,
    62.109375,
    61.5234375,
    60.7421875,
    60.15625,
    59.375,
    58.7890625,
    58.203125,
    57.421875,
    56.8359375,
    56.0546875,
    55.46875,
    54.8828125,
  ]

# LPF
fits_directory: '/data/2020-05-10T05:42:00-05:45:10_all'
# Indices [start, stop] that specify the location of the time-stamp in the filename.
timestamp_start_stop: [0, 21]
# Indices [start, stop] that specify the location of subband in the filename.
subband_start_stop: [24, 28]
n_timesteps: -1
detection_radius: 1024 
image_size: 2300
kappa: 5
center_sigma: 21
scale_sigma: 21
sigma_clipping_maxiter: 1
output_folder: './runs/'
mmap_n_sources: 4096
mmap_n_timesteps: 1024
use_quality_control: false
box_size: 16
separation_crit: 1.
nn_checkpoint: '/afhome/ruhe/projects/lpf/data/nn/epoch_1.ckpt'

# Simulation
nparams: 4
dm_range: [0, 512]
fluence_range: [0.0, 32.0]
width_range: [0, 16]
spec_ind_range: [-4, 4]
simulation_output_folder: "data/transient_sim/a12"
nevents: 16384

# Neural Network
nn_output_folder: "data/nn/"
lr: 0.001
epochs: 32
noise_path: null
noise_multiplier: 1 # Noise value, compare with fluence value.
batch_size: 32
num_workers: 4
