output_folder: 'data/nn/'
device: 'cuda'
nn:
  architecture: [
      # ['conv', in_channels, out_channels, kernel_size, stride, padding]
      ["conv", 1, 8, 1, [1, 1], 0],
      ["act"],
      ["conv", 8, 16, 3, [1, 2], 1],
      ["act"],
      ["conv", 16, 32, 3, [1, 2], 1],
      ["act"],
      ["conv", 32, 64, 3, [2, 2], 1],
      ["act"],
      ["conv", 64, 128, 3, [2, 2], 1],
      ["act"],
      ["conv", 128, 256, 3, [2, 2], 1],
      ["act"],
      ["conv", 256, 512, 3, [2, 2], 1],
      ["act"],
      ["act"],
      ["flatten"],
      ["act"],
      # ['linear', in_features, out_features]
      ["linear", 512, 5],
    ]
trainer:
  lr: 0.001
  epochs: 32

data:
  transient_path: '/home/druhe/release/lpf/data/transient_sim/a6/data.npy'
  parameter_path: '/home/druhe/release/lpf/data/transient_sim/a6/parameters.npy'
  noise_path: '/home/druhe/release/lpf/data/noise/noise.npy'
  noise_multiplier: 1 
  batch_size: 64
  num_workers: 4 
