output_folder: 'data/nn/'
trainer:
  lr: 0.001
  epochs: 32

data:
  transient_path: 'data/transient_sim/a12/data.npy'
  parameter_path: 'data/transient_sim/a12/parameters.npy'
  noise_path: null 
  noise_multiplier: 1 # Noise value, compare with fluence value specified in transient simulation YAML.
  batch_size: 128
  num_workers: 4 
